http:
  host: 0.0.0.0
  port: 8080
auth:
  host: auth
  port: 8081
user:
  host: user
  port: 8082
cors:
  allowed_origins:
  - https://matchlab.space
postgres:
  host: postgres
  port: 5432
  database: matchlab
  user: matchlab
  ssl_mode: disable
  migration_timeout: 5m
