apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: matchlab
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:AEshvrzv5xSc0e9Jtn2xDgbOmGVfBRW8rsM0EDmqQD7TrujF1JEeaRyQ8OiNZduJqVKq13IhTCVQtEF34CI7b2Qj6AepbzKqHmi/LS2jlOBXvDaiakONfK/9Mi2JkPLqpHZBUH2W8oXuWll/puALm4dlARjXwB2fCQF1UWpG50sF7pGPf0+5ciADEnkpBs8/cZUmXpbgv7ELWA8Q7Lq58HpODY4G//5WgCtgpcwx1nkPBW9KOWUAaEde3JqD/Ss=,iv:h8aanpdOlbg6/2Otm5LV7pcR4KBaaO6KYs62eYpwT74=,tag:bE2eKTq9Im+z2NK5+4HHyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscTl2aGNvTUJCUEVCT1po
            Nkw3elRjQ0pJa3dZaFpLeTMwSWJQV2d3TUYwClZ4cm5vREZsM1liRGVlTlIrWm95
            T2RFaE9CdWY2TXJvR1JBc3RSRFE2V28KLS0tIE9PVzFHdFhXK0plMzJpTC9RVmcr
            S1h6WEx4SCtxa3AzeGRxejcrVjV5NnMKnuL5HPo+2nlJP9AlYFngg3T9Byzpi9zO
            nDVl8R86claEalex2vuhL7PUeNXj+FT44pYOMvzQS+J02O30dU7mJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sptzan2vxqnmq848f652fz7jyfh8x0td9v6tsxc24ft6j96lug3spwzt93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T01:40:12Z"
    mac: ENC[AES256_GCM,data:Rbcakth1Ukx2ka9etSvDgIIABvIe6celMFPOp4l64suHzoNzRfOlMpb31/E0xHX+9/yqCaWF/b/rCSFMVPwI1EyJJIjbLLhsXvG7jl54lGq8lzWtxO+jFMYZC003WuC78kNKWm28ZXz9pkCIgpzthtW7ElNjvTARIogFhjGCxok=,iv:fWmPA92EMe/3ad0tJpdPZheGplHjEGgVbersuzafguw=,tag:1dunf3fCylVkc3aQ2/u/og==,type:str]
    version: 3.13.3
