apiVersion: v1
kind: Secret
metadata:
    name: matchlab-postgres
    namespace: matchlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:k9qQjgwhqgbyrkcH7rU/H2rvU5//PKHdP2J97+IQT76VY/26YmUgcFVcmrUCQb4n+qYa+Lv1,iv:794r25w1uoaTGqeMplayzKF0R7kWEnozJPjNDrIVs74=,tag:dZd2heFo406CzHmiIfgV5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMWxibkZxZGVBZ2tqeXBs
            YytXWVYyZnBPamJvQ0E2TEhReWkvSGNRTlVRCjhvZlpQcyttek9kL2s5ZTV0d3NI
            cUpqYUltSjZrZE9uSkkxY29BY0FEdzAKLS0tIHRrcTlPYmJCV1AzRmxPeGM0aVdu
            ajkvYkcrNFdHSnZ0VFdaUUgvY2RidlEKaV1fj/zew+UgmhNs9fiOY98hj1xxlzta
            wlqlZpLul0JbjQsQr8qfgGQxeeo4JD7swayDP0n0i/FnkOE0PbKgUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sptzan2vxqnmq848f652fz7jyfh8x0td9v6tsxc24ft6j96lug3spwzt93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T01:11:34Z"
    mac: ENC[AES256_GCM,data:b4XobmDKnqKR5o5nMmoh5VB/vewiPw6z0dMMBCr0+3enQnliwxpKDklHN4Sntzztwo4fP+/5IxDUlm6u48Ps8tr+tpGSvCvbMUIllkN95wsFCjDEORvsscrSMHGH8o6wPn1qxOjbfaC6qmCBLtfN/c9P839eFuYXTp84FcXs6Cg=,iv:cemcXzAT23tN1eRJrwoOQvoBLhf/rACHlVrGrT0C+/c=,tag:icI6IXufKwS4nlmYHG7HXw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: matchlab-redis
    namespace: matchlab
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:KittrNbE+cvrSTZIGQyVOwtaj3/sb4iFujneLi0O6elcDkM8fIjetHrJ5E20s4CFbiQsNSDv,iv:DrTxJkWlzafNzNyh3icjEUY4gFrMFj93sj+EIabiREY=,tag:ShVcpINSjdJdQfeB00Y0Rg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMWxibkZxZGVBZ2tqeXBs
            YytXWVYyZnBPamJvQ0E2TEhReWkvSGNRTlVRCjhvZlpQcyttek9kL2s5ZTV0d3NI
            cUpqYUltSjZrZE9uSkkxY29BY0FEdzAKLS0tIHRrcTlPYmJCV1AzRmxPeGM0aVdu
            ajkvYkcrNFdHSnZ0VFdaUUgvY2RidlEKaV1fj/zew+UgmhNs9fiOY98hj1xxlzta
            wlqlZpLul0JbjQsQr8qfgGQxeeo4JD7swayDP0n0i/FnkOE0PbKgUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sptzan2vxqnmq848f652fz7jyfh8x0td9v6tsxc24ft6j96lug3spwzt93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T01:11:34Z"
    mac: ENC[AES256_GCM,data:b4XobmDKnqKR5o5nMmoh5VB/vewiPw6z0dMMBCr0+3enQnliwxpKDklHN4Sntzztwo4fP+/5IxDUlm6u48Ps8tr+tpGSvCvbMUIllkN95wsFCjDEORvsscrSMHGH8o6wPn1qxOjbfaC6qmCBLtfN/c9P839eFuYXTp84FcXs6Cg=,iv:cemcXzAT23tN1eRJrwoOQvoBLhf/rACHlVrGrT0C+/c=,tag:icI6IXufKwS4nlmYHG7HXw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: matchlab-smtp
    namespace: matchlab
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:+PWcLVBN6gpdmKMCVpjbTow2S9w=,iv:GvupRx8VXAfO1WWeE/DcESeYMZ2ezYRSame4exFvvjg=,tag:1A+2VLgn3MWk2ZjpI4fUVg==,type:str]
    password: ENC[AES256_GCM,data:C4T6Uw0BgtcZnZ0XFwCtSCTFDipKc+E+j64/qyuZ83uWvWj96xpTyg==,iv:uf9H46/sPvcOXiSaPBZ9jGv71UHPae71f4Lhe6FWI04=,tag:oAy+WtZSW5+bB5j+nIJpxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMWxibkZxZGVBZ2tqeXBs
            YytXWVYyZnBPamJvQ0E2TEhReWkvSGNRTlVRCjhvZlpQcyttek9kL2s5ZTV0d3NI
            cUpqYUltSjZrZE9uSkkxY29BY0FEdzAKLS0tIHRrcTlPYmJCV1AzRmxPeGM0aVdu
            ajkvYkcrNFdHSnZ0VFdaUUgvY2RidlEKaV1fj/zew+UgmhNs9fiOY98hj1xxlzta
            wlqlZpLul0JbjQsQr8qfgGQxeeo4JD7swayDP0n0i/FnkOE0PbKgUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sptzan2vxqnmq848f652fz7jyfh8x0td9v6tsxc24ft6j96lug3spwzt93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T01:11:34Z"
    mac: ENC[AES256_GCM,data:b4XobmDKnqKR5o5nMmoh5VB/vewiPw6z0dMMBCr0+3enQnliwxpKDklHN4Sntzztwo4fP+/5IxDUlm6u48Ps8tr+tpGSvCvbMUIllkN95wsFCjDEORvsscrSMHGH8o6wPn1qxOjbfaC6qmCBLtfN/c9P839eFuYXTp84FcXs6Cg=,iv:cemcXzAT23tN1eRJrwoOQvoBLhf/rACHlVrGrT0C+/c=,tag:icI6IXufKwS4nlmYHG7HXw==,type:str]
    version: 3.13.3
